name: Erlang CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: erlang:26.0
    
    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: rebar3 compile
    - name: Dialyzer
      run: rebar3 dialyzer
    - name: Run tests
      run: rebar3 do xref, eunit
    - name: Coverage
      run: rebar3 do cover, covertool generate
    - name: Codecov
      uses: codecov/codecov-action@v1.0.6
      with:
        file: _build/test/covertool/ephp.covertool.xml
